version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cge_postgres
    restart: always
    environment:
      POSTGRES_USER: cge_admin
      POSTGRES_PASSWORD: cge_password_secure
      POSTGRES_DB: cge_incidencias
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: cge_api
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgres://cge_admin:cge_password_secure@db:5432/cge_incidencias
      - JWT_SECRET=super_secret_key_cge_military
      - NODE_ENV=development
      - WHATSAPP_TOKEN=EAAMFooz0AzEBQSkAM1iXEPNYGgzCMNYjPQIicWjhCKUu54MwMKIlOZCZAkIM2pxfVaSzIu4B3VksyZBklBHrrW1gIgl8f1vyQ461Sgjabr8jNSeEu3FxQTTDzEBNtxijCgjf8bsoD66w3ShNkZAQNE0JaitFZCLbRG2UZAK9nimR1DiBeKGXOOQqkEHRNHu0LkShFR6bzlPGdW7wTfZCaOiTlLCEVpuWhRs09ffp7mDAhFdifT4VSvX3VCknG5pL3USxcBAC3vzZAuohTgDeagrmvpx8hqpnGtBdRQZDZD
      - PHONE_NUMBER_ID=949588524901447
      - WEBHOOK_VERIFY_TOKEN=cge_secret_123
      - FRONTEND_URL=http://10.16.80.50:5174
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: cge_client
    restart: always
    ports:
      - "5174:5173"
    environment:
      - VITE_API_URL=http://10.16.80.50:3001
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:
